### ISSUE TITLE
possible to add HTML snippet to index.html?

### ISSUE THREAD

**Issue by rnuske** [unDocUMeantIt/roxyPackage#20]
Feature wish: I would like to add some guidance (HTML snippet) to index.html underneath the list of our internal R packages. I looked at `roxy.packages(html.options=...)` but couldn't find a way to include my HTML.

**Comment by unDocUMeantIt** [comment]
it's tricky, how would you tell `roxy.package()` where to put your snippet exactly? of course it could be hardcoded so it always ends up below the packages list of that particular file, but that seems to me like a very singular feature. to have this in the package, it should be general enough to be usable for various cases.

but for the time being, you could write a short function to patch your snippet into the file after the `roxy.package()` call in your script.  e.g., `XiMpLe::parseXMLTree()` should be able to parse the file, `XiMpLe::node()`can be used to find and replace the HTML parts you're interested in, and `XiMpLe::pasteXML()` combined with `cat()`can then overwrite the existing file with the altered code.

**Comment by rnuske** [comment]
ahh right, every package added to the repository changes the index.html of the repo. 

I would like to have the HTML snippet underneath the table, so below the entire list of all packages. I have no clue whether this is hard to hack into the html-generating code of roxy.package().

Of course one could change the index.html later on with various tools. It would be just convenient if roxy.package() could do it in the same call.

**Comment by unDocUMeantIt** [comment]
i appreciate your request. it should be possible to do that, but i'm really hesitant because it seems to me like a highly individual request and not so much like something that would generally be helpful to many. in that, it would be a potential cause for future trouble. or you might change your views on where to put the snippet and we would have to change parts of the code again.

so for such a feature to become part of the actual package code base, it should be flexible enough to be useful for all kinds of customizations to the HTML documents. that on the other hand looks like a *lot* of work, so it might be more straight forward to work around this by manuall applying the customization after `roxy.package()` has finished.

**Comment by rnuske** [comment]
okay, i understand your reasoning. roxyPackage is already quite featureful and you have to draw a line somewhere.

Concrete hints how to manipulate index.html with XiMpLe would be very welcome ;-)
